### PR TITLE
Fix contextual_help deprecation notice

### LINKED ISSUE #113: contextual_help is deprecated since version 3.3.0
Copying here for visibility: https://wordpress.org/support/topic/deprecated-use-of-contextual_help/

### PR DESCRIPTION
**Pull request by jessepearson**
Fixes #113 

Updates deprecated hook of `contextual_help` with `add_help_tab` to stop notices.

### CODE REVIEW

**Comment by lkraav** [comment]
This is not the way to go. There is no such core hook as `add_help_tab`, at least as of WP 5.4.

https://developer.wordpress.org/reference/classes/WP_Screen/add_help_tab/ explains the details:

> Call this on the load-$pagenow hook for the relevant screen, or fetch the $current_screen object, or use get_current_screen() and then call the method from the object.

So refactoring towards `load-<our_page_id>` hook needs to happen here instead.

**Comment by jessepearson** [comment]
@lkraav Honestly, I was just going off of the suggestion here:
https://wordpress.org/support/topic/contextual_help-is-deprecated-since-version-3-3-0/#post-12635875 . This plugin is something myself and my company recommends on a daily basis and it's pretty frustrating that it was updated to include ads, but it's not receiving support and also throwing deprecation notices with each admin page click.

**Comment by lkraav** [comment]
Yeah I saw that WP support forum message. I appreciate you kicking off this PR, it made me finally dig through the details as well and I think we know what to do know.

Perhaps @mailpoet could get this wrapped up for us?

**Comment by flakas** [comment]
Hello @jessepearson, @lkraav,

Thank you for the PR and the comments.
It appears that WordPress does not have the used hook `add_help_tab` unlike it had one for the `add_contextual_help` hook ([docs](https://developer.wordpress.org/reference/hooks/contextual_help/)).
By using a non-existent hook this would effectively never load the help tab nor the `Screen options`.

I have taken a slightly different approach to fix the issue in #116, retaining the `Screen options`, but eliminating the help tab.

I will close this PR, but thank you again for your contributions, we definitely appreciate them.

**Pull request closed without merging**
